zeitgeistpm/zeitgeist-subsquid

chain/prediction-markets.ts

The `Market` type doesn's seem to work properly with `DetectType` alias from polkadot.js https://github.com/polkadot-js/api/blob/f6e50f14b5301e8ba23eec0e9059c544de2552ea/packages/types/src/types/detect.ts#L10

explicitly cast createTypeUnsafe to Market

---

mappings/balances.ts

At the block, the event `balances.DustLost` comes before `balances.Transfer` and `system.ExtrinsicSuccess` when the account balance goes below `ExistentialDeposit`. Following this sequence while computing Ztg balance for the account would result in negative balance (as observed for few accounts).
The `DustLostEvent` should technically be captured for the account when the amount is transferred and transaction fees is incurred for executing the transfer from the the same account.

Execute DustLostEvent after ExtrinsicSuccessEvent

---

schema.graphql
src/model/generated/account.model.ts

Using `@derivedFrom` annotation while nesting entities in an entity creates recursive references which gets prone to manual attacks by any user as discussed in #63.
Avoiding them would help in processing query requests with much ease.

Remove recursive ref for account balances

---

src/processor/index.ts
src/processor/postHooks.ts

As discussed at https://github.com/zeitgeistpm/zeitgeist/issues/444
This PR sets a stage for post block hooks in order to manually consider data which hasn't been recorded by any event.

Manually fix balances to record activity unavailable via event/extrinsic data

---

.env
src/processor/balances.ts

it's used only in `initBalance` as I see, could be wrong, but if that's the case it can be replaced with an rpc call to sdk.
This also helps when indexing different node, e.g. local node

Remove environment variable BLOCK_ZERO

---

src/processor/index.ts
src/processor/postHooks.ts

PostHooks at block numbers before `#588249` for adding balances to account `dE4NbK6XC4dJEkjU5erpDNj2ydMh1fMNw8ug7xNgzTxqFo5iW` as stated at https://github.com/zeitgeistpm/zeitgeist/issues/444.

Reconcile balances before `zeitgeist:0.2.4`

---

src/processor/index.ts
src/processor/markets.ts
src/types/events.ts
typegen.json

Process `Event::MarketClosed` (introduced on `v37`) emitted when the market ends. 
Trading is not allowed on markets that are closed.

Process & map MarketClosedEvent

---

src/processor/index.ts
src/processor/markets.ts
src/types/events.ts
typegen.json

This event hasn't been emitted yet on-chain. And post `v36` [release](https://github.com/zeitgeistpm/zeitgeist/releases/tag/v0.3.2), the chain has removed it completely.

Detach MarketCancelledEvent

---

src/processor/swaps.ts

These params were added on events after some time, however subsquid failed to pick them up which resulted in spot prices going crazy. This PR ensures they are stitched and secured.

Map baseAssetAmount & assetOut/assetIn from event params

---

src/processor/swaps.ts

The balance seem to be correctly mapped on accounts schema but not on pools schema. Type for `ztgQty` has been set as detected as a param on `PoolCreatedEvent`

Update type for ztgQty on pool creation

---

src/mappings/predictionMarkets/index.ts

Based on firesquid changes, `scalarType` has been remapped.
Resolves https://github.com/zeitgeistpm/ui/pull/218#issuecomment-1298499909

Remap `market.scalarType`

---

src/mappings/predictionMarkets/index.ts

Closes #254. `tokens.Deposited` events have been released along with the event `predictionMarkets.boughtCompleteSet` since the inception of `specVersion:36`. Hence accordingly, handler has been modified to pick this change.

Avoid multiple balance changes post mapping of TokensDepositedEvent

---

schema.graphql
src/mappings/helper.ts
src/mappings/predictionMarkets/index.ts
src/model/generated/_marketType.ts

Closes #261
Follows [changelog](https://github.com/zeitgeistpm/zeitgeist/blob/main/docs/changelog_for_devs.md#v037):
```
Transformed integer scalar markets to fixed point with ten digits after the decimal point.
As soon as this update is deployed, the interpretation of the scalar values must be changed.
```

Rescale bounds and resolved-outcome for old scalar markets

---

src/server-extension/query.ts
src/server-extension/resolvers/priceHistory.ts

This removes the need to include each price change for a particular asset. The prices are picked directly from `HistoricalAsset` by comparing timestamps.

Optimize query for price history

---

src/server-extension/query.ts

Closes #323. Changes the lookup field for ordering historical prices from `timestamp` to `id`
Price history failed to pick the correct value when there are multiple prices stored as a record for a single block number or timestamp (i.e., when multiple trades happen on the same block). In such a scenario, `id` would be the unique field on `HistoricalAsset` to consider timestamp as well as position in the block.

Order prices by id rather than timestamp

---

scripts/subscribe/proposedMarkets.ts

The query now captures the latest market which has been proposed instead of all markets which are still in proposed state.

Fix redundant subscription alerts 

---

db/migrations/1682400128837-Data.js
db/migrations/1682401174187-Data.js
schema.graphql
src/mappings/swaps/index.ts
src/model/generated/historicalAsset.model.ts
src/model/generated/pool.model.ts

- Introduces new field `baseAssetTraded` as a replacement for `ztgTraded`
- Makes pool account's `accountId` non-nullable on pool schema

Add `baseAssetTraded` on `HistoricalAsset`

---

src/mappings/helper.ts
src/mappings/predictionMarkets/index.ts
src/processor.ts

- Addresses rewards received by `dE36Y98QpX8hEkLANntbtUvt7figSPGxSrDxU4sscuX989CTJ` on main node before `specVersion:33`
- Improves inclusion of `ParachainStaking.Rewarded`

Handle rewarded events for specVersion < 33

---

src/mappings/predictionMarkets/index.ts
src/mappings/predictionMarkets/types.ts
src/processor.ts
src/types/calls.ts
typegen.json

Pull in `PredictionMarkets.redeem_shares` from archive as a substitute for `PredictionMarkets.TokensRedeemed` before `specVersion:35`. Closes #377.

Process & map PredictionMarketsRedeemSharesCall

---

src/mappings/predictionMarkets/index.ts
src/processor.ts

If `origin` is not present on call `PredictionMarkets.redeem_shares`, extract public key of account making the call from extrinsic signature. This is likely to happen for calls sent in a batch.

Lookup `redeem_shares` extrinsic for accountId

---

schema.graphql
src/mappings/predictionMarkets/index.ts
src/model/generated/_marketBonds.ts

Closes #370. As discussed in the node/infra meeting:
```
Permissionless bonds are settled when the market is destroyed or resolved.
Advisory bonds are settled when the market is approved, rejected or expired.
Oracle bonds settle when the market resolves or is destroyed.
```
P.S: This should be automatically handled using events once they are made available on-chain.

Settle market bonds during market lifecycle

---

src/mappings/balances/index.ts
src/mappings/currency/index.ts
src/mappings/parachainStaking/index.ts
src/mappings/postHooks/marketDestroyed.ts
src/mappings/postHooks/marketResolved.ts
src/mappings/predictionMarkets/index.ts
src/mappings/styx/index.ts
src/mappings/swaps/index.ts
src/mappings/system/index.ts
src/mappings/tokens/index.ts
src/processor.ts

This PR ensures token balance changes from event handlers are updated in batches. This brings us closer to utilising the advantages of `SubstrateBatchProcessor`. Entity ID for `Account` and `AccountBalance` will not include eventId now.

Asynchronously update tokens balances

---

db/migrations/1686976504351-Data.js
schema.graphql
src/mappings/swaps/index.ts
src/model/generated/historicalPool.model.ts
src/model/generated/market.model.ts
src/model/generated/pool.model.ts

- Pool `status` with stricter typing (Follows #356)
- Ensure non-null values inside `weights` and `categories` (Follows https://github.com/zeitgeistpm/sdk-next/issues/23)

Add non-null checks and replace pool-status

---

scripts/subscribe/disburseZtg.ts

This has been applied to `disburseZtg` script to work only on data that have been recorded in the last 72 hours. It is assumed that data before 72 hours is already logged on cache db.

Filter subscribed records by timestamp

---

schema.graphql
src/mappings/predictionMarkets/index.ts
src/mappings/predictionMarkets/types.ts
src/model/generated/_marketBonds.ts
src/types/events.ts
src/types/storage.ts
src/types/v46.ts
typegen.json

- Adapt to on-chain market struct changes
- Fetch market via storage call `MarketCommons.Markets` when reported (if required)
- Settle outsider-bond during market resolution and destruction (if applicable)

Include outsider-bond and specVersion:46 changes

---

src/server-extension/query.ts

- This should reduce dependency on asset schema and further provide accurate computation. 
- The query should also resolve stats for expired markets. Resolves #438

Utilise balances from pool account when computing liquidity

---

src/mappings/helper.ts
src/mappings/util.ts
src/server-extension/query.ts
src/server-extension/resolvers/index.ts
src/server-extension/resolvers/marketMetadata.ts

Serves as a backup and validation tool for content stored in IPFS. Closes #437.

Allow querying cached metadata on redis

---

schema.graphql
src/mappings/predictionMarkets/index.ts
src/mappings/predictionMarkets/types.ts
src/model/generated/_marketReport.ts
src/types/events.ts
src/types/storage.ts
src/types/v49.ts

`PredictionMarkets.MarketDisputed` event can be handled without report. 
**Fixes**
**Based on https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbsr.zeitgeist.pm#/explorer/query/4292260**

Digest MarketDisputedEvent without report

---

src/mappings/assetTxPayment/index.ts
src/mappings/assetTxPayment/types.ts

Adapt to incoming  `specVersion:49` changes for storage call AssetRegistryMetadataStorage connected to event `AssetTxPayment.AssetTxFeePaid`. This should debug mapping of the event.

Init latest types for AssetRegistryMetadataStorage

---

src/mappings/balances/index.ts
src/processor.ts

As noticed, each event `Swaps.MarketCreatorFeesPaid` accompanies with the event `Balances.Transfer` to capture same transaction. Sequentially, it means that `BalancesTransferEvent` would be processed before `SwapsMarketCreatorFeesPaidEvent`. 
This PR refurbishes the already processed record. Closes #434.

Process `Swaps.MarketCreatorFeesPaid`

---

src/mappings/assetTxPayment/index.ts
src/mappings/helper.ts
src/processor.ts

As noticed [on-chain](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbsr.zeitgeist.pm#/explorer/query/4287409), transaction fees recorded by event `AssetTxPayment.AssetTxFeePaid` are collected by the treasury account.

Record asset txn fee deposits in treasury account

---

src/mappings/currency/index.ts
src/mappings/helper.ts
src/mappings/tokens/index.ts
src/mappings/tokens/types.ts
src/processor.ts

Fixes the below error: 
```
{
"level": 5,
"time": 1698810802164,
"ns": "sqd:processor",
"err": {
"stack": "TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))\n    
at Object.getTokensTransferEvent (/home/zeitgeist-squid/lib/mappings/tokens/types.js:104:40)\n    
at Object.tokensTransfer (/home/zeitgeist-squid/lib/mappings/tokens/index.js:60:55)\n    
at /home/zeitgeist-squid/lib/processor.js:585:52\n    
at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    
at async TypeormDatabase.runTransaction (/home/zeitgeist-squid/node_modules/@subsquid/typeorm-store/lib/database.js:110:13)\n    
at async TypeormDatabase.transact (/home/zeitgeist-squid/node_modules/@subsquid/typeorm-store/lib/database.js:64:24)\n    
at async Runner.process …
```

Ensure types coverage above specVersion:51

---

schema.graphql
src/mappings/helper.ts
src/mappings/predictionMarkets/index.ts
src/mappings/predictionMarkets/types.ts
src/model/generated/_marketBonds.ts

As noticed on chain storage,
- Post `specVersion:42`, dispute bond will be available in `market.bonds`. Closes #449
- Post `specVersion:49`, dispute information will not be available in `market.disputes`. Freezes #302

Set conditions for dispute-bond and disputes

---

src/server-extension/query.ts
src/server-extension/resolvers/marketStats.ts

Adds `traders` to `marketStats`. Accomplishes #489

Resolve traders count

---

src/mappings/neo-swaps/index.ts

Post deployment of `specVersion:53` and storage migration of some markets from `AMM` to `Lmsr` pool, this PR removes the redundant assets arising out of multiple pools attached to the same market.
An example, `marketId:287` having redundant assets:

Remove swap assets before attaching neo-swap assets

---

src/mappings/authorized/index.ts
src/mappings/prediction-markets/index.ts

Setting fields on `OutcomeReport` as `null` got compiled and saved on db without error. But failed while fetching records from postgres (db) posing as runtime error hidden within markets query. Fixes #513

Debug initialisation of OutcomeReport

---

src/helper.ts
src/main.ts
src/mappings/balances/index.ts
src/post-hooks/balancesUnreserved.ts
src/post-hooks/index.ts
src/post-hooks/initBalance.ts
src/processor.ts

This should eliminate calls to polkadot.js api for retrieving balance of all accounts at genesis block. Thus, should give little boost to the processor in terms of sync speed.

Hook genesis balances

---

src/main.ts
src/mappings/balances/index.ts
src/mappings/styx/index.ts
src/mappings/system/decode.ts
src/mappings/system/index.ts
src/processor.ts
src/types/system/events.ts
typegen.json

Post #517 and with this PR, accounts can be initialised asynchronously as and when first on-chain transaction is processed. Therefore, there's no need to forcefully initialise account based on event `System.NewAccount`.

Unmap SystemNewAccountEvent

---

src/helper.ts
src/main.ts
src/mappings/prediction-markets/helper.ts
src/mappings/prediction-markets/index.ts
src/post-hooks/index.ts
src/post-hooks/marketResolved.ts
src/post-hooks/resolveMarket.ts

As monitored via logs, a lot of transactions happen after market is resolved. Therefore, batching them would help ease synchronisation for processor.

Async save changes from market resolution

---

src/server-extension/query.ts

Prices for migrated pool markets seemed distorted on UI due to constraints being set based on timestamps of deployment of pool and market resolution. 
However, for all markets there would be one record for market-creation and another for market-resolved on `HistoricalMarket`. This PR utilises timestamp from these two records to set upper and lower limit while computing asset prices vs timestamp. Closes #516

Set price range between market-creation and resolution

---

src/server-extension/helper.ts
src/server-extension/resolvers/assetPrice.ts
src/util.ts

UI has it embedded in their logic to fetch real-time prices of assets from Coingecko. But for development purposes, it would be fine to use default price (currently set as 1) without bothering the Subsquid logic (which fetches price from redis-db before hitting Coingecko). 
This PR allows UI to fetch default price for development purposes (via app-docker).

Open AssetPriceResolver for app-docker

---

src/helper.ts
src/mappings/neo-swaps/index.ts
src/mappings/swaps/index.ts

This should help ordering of assets connected to market by `id_ASC` in allegiance with on-chain order. Closes #536

Reframe id on asset and save together on pool creation

---

src/consts.ts
src/server-extension/helper.ts
src/server-extension/query.ts

Since the value of WSX asset is $0, so it wouldn't make sense to show it as dollar denominated volume

Reconsider volume coming from wsx markets

---

src/helper.ts

Adapts `formatAssetId` to include parameters from `balanceInfo` resolver
Fixes:

Fix balanceInfo resolver

---

src/mappings/court/decode.ts
src/mappings/court/index.ts
src/types/court/storage.ts
src/types/storage.ts
typegen.json

As courtId is absent on `Court.CourtOpened` event, it would be necessary to query the same on-chain while initialising court object

Query court storage `marketIdToCourtId`
