zeitgeistpm/zeitgeist-subsquid

- chain/index.ts
- chain/prediction-markets.ts
- chain/swaps.ts
- db/migrations/1636380839088-init.ts
- generated/model/index.ts
- generated/modules/pool/pool.model.ts
- generated/modules/pool/pool.resolver.ts
- generated/modules/pool/pool.service.ts
- generated/warthog/binding.ts
- generated/warthog/classes.ts
- generated/warthog/schema.graphql
- manifest.yml
- mappings/index.ts
- schema.graphql
> Process & map swaps.PoolCreate

- chain/prediction-markets.ts
- generated/model/index.ts
- generated/modules/enums/enums.ts
- generated/modules/market-history/market-history.model.ts
- generated/warthog/binding.ts
- generated/warthog/classes.ts
- generated/warthog/schema.graphql
- manifest.yml
- mappings/markets.ts
- schema.graphql
> Process MarketDisputedEvent & BoughtCompleteSetEvent

- chain/prediction-markets.ts
- generated/modules/enums/enums.ts
- manifest.yml
- mappings/markets.ts
- schema.graphql
> Process MarketApprovedEvent

- chain/prediction-markets.ts
- generated/modules/enums/enums.ts
- manifest.yml
- mappings/markets.ts
- schema.graphql
> Process MarketStartedWithSubsidyEvent & MarketCancelledEvent

- chain/prediction-markets.ts
- generated/modules/enums/enums.ts
- manifest.yml
- mappings/markets.ts
- schema.graphql
> Process MarketRejectedEvent & SoldCompleteSetEvent

- chain/currency.ts
- chain/index.ts
- db/migrations/1637558672297-init.ts
- generated/model/index.ts
- generated/modules/account/account.model.ts
- generated/modules/account/account.resolver.ts
- generated/modules/account/account.service.ts
- generated/modules/asset-balance/asset-balance.model.ts
- generated/modules/asset-balance/asset-balance.resolver.ts
- generated/modules/asset-balance/asset-balance.service.ts
- generated/modules/historical-asset-balance/historical-asset-balance.model.ts
- generated/modules/historical-asset-balance/historical-asset-balance.resolver.ts
- generated/modules/historical-asset-balance/historical-asset-balance.service.ts
- generated/warthog/binding.ts
- generated/warthog/classes.ts
- generated/warthog/schema.graphql
- manifest.yml
- mappings/balances.ts
- mappings/index.ts
- schema.graphql
> Process & map CurrencyTransferredEvent

- chain/index.ts
- chain/tokens.ts
- manifest.yml
- mappings/balances.ts
> Process & map TokensEndowedEvent

- chain/currency.ts
- chain/index.ts
- manifest.yml
- mappings/balances.ts
> Process CurrencyDepositedEvent & CurrencyWithdrawnEvent

- chain/balances.ts
- chain/index.ts
- manifest.yml
- mappings/balances.ts
> Process BalancesEndowedEvent & BalancesTransferEvent

- chain/balances.ts
- manifest.yml
- mappings/balances.ts
> Process BalanceSetEvent

- chain/balances.ts
- manifest.yml
- mappings/balances.ts
> Process BalancesReservedEvent & BalancesUnreservedEvent

- chain/index.ts
- chain/system.ts
- manifest.yml
- mappings/balances.ts
- mappings/index.ts
- mappings/markets.ts
- mappings/util.ts
- package.json
- yarn.lock
> Consider txn fees while calculating asset balances of account

- mappings/markets.ts
fixes #42 
Currently, no explicit event is emitted for tokens transfer to the account which has bought assets for a particular market using extrinsic `predictionMarkets.buyCompleteSet`.
Only if the token is not existing in the account, the default event `tokens.Endowed` is emitted.
A check has been added to ensure processor considers this scenario and updates the balances accordingly.
Some examples -
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbsr.zeitgeist.pm#/explorer/query/851
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbsr.zeitgeist.pm#/explorer/query/14813
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbsr.zeitgeist.pm#/explorer/query/26084
> Update balances based on extrinsic predictionMarkets.buyCompleteSet

- mappings/balances.ts
- mappings/markets.ts
- mappings/util.ts
- package.json
- yarn.lock
closes #44 
This PR sets a stage for caching. This has saved a lot of processing time in my local.
I have tested the redis client with the server hosted on the parent machine.  We can also consider hosting redis db as a separate docker container within the framework of processor. Going forward, there will be improvements on the way we are caching data.
> Setup cache on redis db

- chain/prediction-markets.ts
- chain/swaps.ts
- manifest.yml
- mappings/balances.ts
- mappings/markets.ts
- package.json
swap event changes: https://github.com/zeitgeistpm/zeitgeist/pull/391/files#diff-f4047ede75a61ea84834bf3adb208fa8b43eed257134cfa80ee12519125c856b
prediction-market event changes: https://github.com/zeitgeistpm/zeitgeist/pull/415/files#diff-f5399e482d98142f978aa63b3dbf82e342f9ddd7bd31c4aa3c1c28c26b83d743R1269-R1292
> Incorporate latest event types

- chain/system.ts
- manifest.yml
- mappings/balances.ts
Value addition for #20 
- Mapping accounts which have been created and captured in the block
- Will help in initialising the Ztg balance of the account
> Process & map NewAccountEvent

- chain/prediction-markets.ts
- manifest.yml
- mappings/markets.ts
connected to #6 as part of Zeitgeist v0.2.2
> Process & map MarketResolvedEvent

- mappings/markets.ts
> Update balances based on extrinsic predictionMarkets.sellCompleteSet 

- chain/swaps.ts
- manifest.yml
- mappings/swaps.ts
> Process PoolJoinEvent & PoolExitEvent

- .gitignore
- package.json
- src/types/events.ts
- src/types/support.ts
- src/types/v23.ts
- src/types/v29.ts
- src/types/v32.ts
- tsconfig.json
- yarn.lock
This PR fixes issues with `Range`, `RangeInclusive`.
> upgrade dependencies

- src/processor/markets.ts
- src/processor/swaps.ts
In sync with changes pushed via https://github.com/zeitgeistpm/zeitgeist/pull/442
Utilising types from https://github.com/zeitgeistpm/tools/pull/150
> Adapt to v14 metadata changes

- src/processor/balances.ts
- src/processor/markets.ts
> Fix assetId for scalar markets

- src/processor/balances.ts
- src/processor/index.ts
> Process & map ParachainStakingRewardedEvent

- src/processor/swaps.ts
for #91 
cc : @Robiquet @numacoding
> Put price as zero when asset qty is zero

- db/migrations/1647091040781-init.js
- schema.graphql
- src/model/generated/account.model.ts
- src/processor/balances.ts
- src/processor/markets.ts
- src/processor/postHooks.ts
- src/processor/swaps.ts
> Identify pool account

- schema.graphql
- src/model/generated/_categoryMetadata.ts
- src/model/generated/_marketDisputeMechanism.ts
- src/model/generated/_marketPeriod.ts
- src/model/generated/_marketReport.ts
- src/model/generated/_marketType.ts
- src/model/generated/_outcomeReport.ts
- src/model/generated/_weight.ts
- src/model/generated/account.model.ts
- src/model/generated/accountBalance.model.ts
- src/model/generated/asset.model.ts
- src/model/generated/historicalAccountBalance.model.ts
- src/model/generated/historicalAsset.model.ts
- src/model/generated/historicalMarket.model.ts
- src/model/generated/historicalPool.model.ts
- src/model/generated/market.model.ts
- src/model/generated/pool.model.ts
> Embed documentation in `schema.graphql`

- db/migrations/1647968539330-init.js
- package.json
- schema.graphql
- src/model/generated/accountBalance.model.ts
- src/model/generated/historicalAccountBalance.model.ts
- src/processor/balances.ts
- src/processor/markets.ts
- src/processor/postHooks.ts
> Compute value of each asset in an account

- db/migrations/1648208750235-init.js
- schema.graphql
- src/model/generated/account.model.ts
- src/model/generated/historicalAccountBalance.model.ts
- src/processor/balances.ts
- src/processor/markets.ts
- src/processor/postHooks.ts
> Compute sum of all asset values in an account

- src/processor/swaps.ts
Replace forEach with map function
Closes #111 as described in https://stackoverflow.com/a/67582696
> Use Promise.all to wrap all async codes

- indexer/docker-compose.local.yml
- scripts/run_processor_local.sh
- src/processor/balances.ts
- src/processor/markets.ts
- src/processor/util.ts
fixes issue with inability to read metadata from local ipfs node when dev environment is ran
> Dev env ipfs fix

- indexer/docker-compose.yml
- package.json
- scripts/run_processor.sh
- scripts/run_processor_local.sh
- src/processor/markets.ts
- src/processor/testnet/index.ts
- src/processor/testnet/postHooks.ts
> Stage processor for battery station

- src/processor/balances.ts
> Adapt `pvalue` to accommodate large dev balances

- scripts/run_processor_local.sh
- src/processor/markets.ts
For #120 
- Run typeorm query to find asset holder accounts and balances
- Fix SyntaxError for non-JSON market data received from IPFS
> Update balances of losing asset holders

- src/processor/markets.ts
- src/processor/testnet/index.ts
- src/types/events.ts
- src/types/v35.ts
- typegen.json
Move outcome asset balance to ztg balance
Example: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbsr.zeitgeist.pm#/explorer/query/1106225
> Process & map TokensRedeemedEvent

- src/processor/markets.ts
> Update balances of winning asset holders

- src/processor/swaps.ts
> Fix zero price due to incorrect `newAssetQty`

- .env
> Add env variable PROCESSOR_PROMETHEUS_PORT

- db/migrations/1659271536695-init.js
- db/migrations/1659276620745-init.js
- schema.graphql
- src/model/generated/historicalPool.model.ts
- src/processor/index.ts
- src/processor/markets.ts
- src/processor/swaps.ts
- src/types/events.ts
- typegen.json
Lined up with #139 
Follows [release v37](https://github.com/zeitgeistpm/zeitgeist/releases/tag/v0.3.3)
> Process & map MarketExpiredEvent & PoolClosedEvent

- src/processor/util.ts
- test/validateBalances.ts
> Validate account balances with polkadot.js

- test/validateBalances.ts
- test/validateHistoricalBalances.ts
> Validate balance history of an account with polkadot.js

- package.json
- scripts/processor.sh
- scripts/query-node.sh
> Add query-node.sh

- src/processor/swaps.ts
> Remove swap fees from calcSpotPrice

- src/processor/balances.ts
- src/processor/index.ts
> Debug computation for DustLostEvent on testnet & mainnet

- test/findChangeInBalance.ts
> Add findChangeInBalance.ts

- .gitignore
- scripts/processor.sh
- scripts/query-node.sh
- test/validateBalances.ts
- test/validateHistoricalBalances.ts
- Allow certificate verification for graphql endpoints
- Add config for restarting processor
- Improve logging for test scripts
- Fix redundant errors for balance history validation
> Improve scripts

- src/processor/balances.ts
- src/processor/index.ts
- src/types/events.ts
- typegen.json
`balances.Deposit` event has been sighted on main-net following validation checks on few accounts. This PR would include them when composing portfolio for an account.
> Process & map BalancesDepositEvent

- schema.graphql
- src/model/generated/_outcomeReport.ts
- src/processor/markets.ts
> Accommodate large int values for `outcomeReport.scalar`

- src/mappings/helper.ts
- src/mappings/swaps/index.ts
- src/processor.ts
> Compute spot prices based on assetIn/assetOut params

- src/mappings/swaps/index.ts
- src/mappings/swaps/types.ts
- src/processor.ts
- src/types/events.ts
- typegen.json
> Process & map PoolActiveEvent

- src/mappings/predictionMarkets/index.ts
> Upgrade handlers bought/sold-CompleteSet

- test/findChangeInTokenBalance.ts
- test/validateHistoricalAssets.ts
- test/validateSpotPrices.ts
> Add validation scripts

- src/mappings/helper.ts
- src/mappings/swaps/index.ts
> Add versatility to swap handlers

- src/mappings/predictionMarkets/index.ts
- src/mappings/predictionMarkets/types.ts
- src/processor.ts
- src/types/events.ts
- src/types/v23.ts
- src/types/v26.ts
- typegen.json
Closes #203 
Market status changes to `Destroyed` as soon as `predictionMarkets.MarketDestroyed` is processed.
> Process & map MarketDestroyedEvent

- package.json
- yarn.lock
> Bump sdk from 0.5.0 to 0.9.1

- src/mappings/tokens/index.ts
- src/mappings/tokens/types.ts
- src/processor.ts
- src/types/events.ts
- typegen.json
> Process & map TokensTransferEvent

- src/mappings/postHooks/marketDestroyed.ts
- src/processor.ts
> Reconcile destroyed markets on testnet

- src/mappings/postHooks/balancesUnreserved.ts
- src/processor.ts
> Unreserve test balances based on account validation checks

- src/mappings/balances/index.ts
- src/mappings/balances/types.ts
- src/processor.ts
- src/types/events.ts
- typegen.json
Adapted from #162 considering #164
> Process & map BalancesDepositEvent on testnet

- src/mappings/parachainStaking/index.ts
- src/mappings/parachainStaking/types.ts
- src/processor.ts
> Connect events on balance addition due to rewards

- src/processor.ts
> Disconnect BalancesSlashed event from processor

- src/mappings/parachainStaking/index.ts
- src/processor.ts
The changes have been set only for testnet. Closes #224 based on #222
> Remap RewardedEvent for specVersion < 33

- db/migrations/1669026248822-Data.js
- schema.graphql
- src/mappings/swaps/index.ts
- src/model/generated/market.model.ts
Pool details would be available via market query, thus clearing passage for #227
> Join pool schema to market schema

- src/mappings/styx/index.ts
- src/mappings/styx/types.ts
- src/processor.ts
- src/types/events.ts
- typegen.json
Debit ztg amount from the portfolio as soon as `styx.AccountCrossed` is encountered. Closes #229
> Process & map StyxAccountCrossedEvent

- db/migrations/1669740680334-Data.js
- schema.graphql
- src/mappings/swaps/index.ts
- src/model/generated/historicalPool.model.ts
> Record differences in volume on historicalPool schema

- src/mappings/predictionMarkets/index.ts
- src/mappings/predictionMarkets/types.ts
- src/mappings/swaps/types.ts
- src/mappings/tokens/types.ts
- src/types/events.ts
- src/types/v41.ts
- Structural changes on `Asset` and `DisputeMechanism`
- New param on `MarketRejectedEvent`
> Adapt to latest changes on specVersion:41

- src/mappings/swaps/index.ts
- src/mappings/swaps/types.ts
> Fix pool account mapping

- src/mappings/predictionMarkets/index.ts
> Stop updating outcome report on resolution

- src/mappings/swaps/index.ts
- src/mappings/swaps/types.ts
- src/processor.ts
- src/types/events.ts
- typegen.json
Fixes #247. Maps `amount` parameter to move funds into or out of the prize pool and burn/mint full sets of outcome respectively.
> Process & map ArbitrageBuyBurnEvent & ArbitrageMintSellEvent

- src/mappings/tokens/index.ts
- src/mappings/tokens/types.ts
- src/processor.ts
- src/types/events.ts
- src/types/v36.ts
- typegen.json
> Process & map TokensDepositedEvent & TokensWithdrawnEvent

- src/mappings/swaps/index.ts
Adapt to changes incurred due to automated on-chain arbitrage
> Update spot price on arbitrage

- scripts/detect/changeInZtgBalance.ts
- scripts/validate/tokenBalances.ts
- scripts/validate/ztgBalances.ts
> Script to validate token balances of all accounts

- src/mappings/swaps/index.ts
As per changes observed on-chain, balances of all accounts holding the tokens are updated to zero post pool and market destruction. Closes #260
> Update asset and all token holding accounts

- src/mappings/predictionMarkets/index.ts
> Stop deleting tokens post `v0.3.6`

- src/mappings/swaps/index.ts
> Adapt pool exit after market resolution

- src/mappings/swaps/index.ts
> Map assets in PoolAssetsEvent when updating amounts

- db/migrations/1674281055850-Data.js
- schema.graphql
- src/mappings/swaps/index.ts
- src/model/generated/historicalPool.model.ts
> Fix pool-status history

- src/mappings/tokens/index.ts
- src/mappings/tokens/types.ts
- src/processor.ts
- src/types/events.ts
- typegen.json
> Process & map TokensBalanceSetEvent

- src/mappings/swaps/index.ts
- src/mappings/swaps/types.ts
- src/processor.ts
- src/types/events.ts
- src/types/v23.ts
- src/types/v26.ts
- src/types/v32.ts
- src/types/v35.ts
- src/types/v41.ts
- typegen.json
Closes #272. Would be helpful in adapting spot prices on addition of Ztg to the pool (as currently observed on-chain)
> Process & map PoolJoinWithExactAssetAmountEvent

- src/mappings/swaps/index.ts
Correctly set `asset.amountInPool` on pool creation
> Debug #281

- package.json
- scripts/validate/tokenBalances.ts
- scripts/validate/ztgBalances.ts
- yarn.lock
- Used axios instead of https for sending request to query node
- Used map instead of for loop for iterating all squid account balances
- Improved logging
> Reform balances validation script

- db/migrations/1675578854712-Data.js
- schema.graphql
- src/mappings/balances/index.ts
- src/mappings/currency/index.ts
- src/mappings/helper.ts
- src/mappings/parachainStaking/index.ts
- src/mappings/postHooks/balancesUnreserved.ts
- src/mappings/predictionMarkets/index.ts
- src/mappings/styx/index.ts
- src/mappings/swaps/index.ts
- src/mappings/system/index.ts
- src/mappings/tokens/index.ts
- src/model/generated/account.model.ts
- src/model/generated/accountBalance.model.ts
- src/model/generated/asset.model.ts
- src/model/generated/historicalAccountBalance.model.ts
- src/model/generated/historicalAsset.model.ts
> Remove asset balance value and account portfolio value

- package.json
- src/server-extension/resolvers/index.ts
- yarn.lock
> Resolve market participants

- src/server-extension/query/index.ts
- src/server-extension/resolvers/index.ts
> Resolve market liquidity

- src/server-extension/query.ts
- src/server-extension/resolvers/index.ts
- src/server-extension/resolvers/marketStats.ts
- src/server-extension/resolvers/stats.ts
> Resolve total liquidity

- src/server-extension/query.ts
- src/server-extension/resolvers/stats.ts
> Resolve total volume

- src/server-extension/query.ts
- src/server-extension/resolvers/index.ts
- src/server-extension/resolvers/priceHistory.ts
Pick last change per block (from asset history) for inflating price chart. Closes #264
> Resolve asset price history

- src/server-extension/helper.ts
- src/server-extension/query.ts
- src/server-extension/resolvers/marketStats.ts
- src/server-extension/resolvers/priceHistory.ts
Get prices of all assets connected to the same market and aligned by their common timestamp
> Allow querying asset prices by market-id

- db/migrations/1679760010426-Data.js
- schema.graphql
- src/mappings/predictionMarkets/index.ts
- src/mappings/swaps/index.ts
- src/model/generated/_marketBonds.ts
- src/model/generated/asset.model.ts
> Create asset with pool

- src/mappings/predictionMarkets/index.ts
> Save market before updating assets while handling market-resolved event

- db/migrations/1680523244714-Data.js
- schema.graphql
- src/mappings/balances/index.ts
- src/mappings/currency/index.ts
- src/mappings/helper.ts
- src/mappings/parachainStaking/index.ts
- src/mappings/postHooks/balancesUnreserved.ts
- src/mappings/predictionMarkets/index.ts
- src/mappings/styx/index.ts
- src/mappings/swaps/index.ts
- src/mappings/system/index.ts
- src/mappings/tokens/index.ts
- src/model/generated/historicalAccountBalance.model.ts
> Purge balance on HistoricalAccountBalance

- scripts/subscribe/marketStatus.ts
> Subscribe to market status

- src/mappings/balances/index.ts
Set new balance and use it for computing difference in balance
> Debug `d_balance` for BalancesBalanceSetEvent

- src/server-extension/resolvers/priceHistory.ts
> Strengthen types for price history

- src/mappings/system/index.ts
This PR fixes the fee computation existing on few accounts for transactions done before block number 588249
> Remove txn fees against Sudo & ParachainSystem extrinsics

- db/migrations/1682002234889-Data.js
- schema.graphql
- src/mappings/helper.ts
- src/mappings/predictionMarkets/index.ts
- src/mappings/swaps/index.ts
- src/model/generated/_weight.ts
- src/model/generated/historicalPool.model.ts
- src/model/generated/pool.model.ts
Introduces new fields `baseAssetQty`, `weight` as a replacement for `ztgQty`, `len`.
> Adapt base asset to consider `ForeignAsset`

- src/mappings/balances/index.ts
- src/mappings/helper.ts
- src/processor.ts
- Progress is cached and
- Balances are updated at the end of each batch
- However, balances are saved as soon as `Balances.BalanceSet` is detected
> Asynchronously map BalancesDepositEvent

- src/mappings/balances/index.ts
- src/mappings/helper.ts
- src/processor.ts
> Optimise balance based events

- src/server-extension/query.ts
- src/server-extension/resolvers/marketStats.ts
- Closes #338
- Migrates type from `Float` to `Int` for `marketId` & `participants`
> Strengthen types of market stats

- scripts/deploy/api.sh
Adds command to copy following lines from local to running containers. Follows #347.
```
if (validatorOptions.forbidUnknownValues !== true) {
validatorOptions.forbidUnknownValues = false;
}
```
> Automate temporary fix for type-graphql issue

- db/migrations/1683167266944-Data.js
- schema.graphql
- src/mappings/predictionMarkets/index.ts
- src/model/generated/market.model.ts
Closes #346. `isMetaComplete` will be `false` if :
- Metadata is not pinned on IPFS
- Categories data is absent
- A category doesn't have `name`
> Create flag to validate metadata compatibility 

- src/mappings/balances/index.ts
- src/mappings/helper.ts
- src/mappings/parachainStaking/index.ts
- src/mappings/system/index.ts
- src/processor.ts
> Optimise System & ParachainStaking events

- src/processor.ts
- Activates `ParachainStakingRewardedEvent` for main & bsr processor
- Replaces `BalancesDepositEvent` with `ParachainStakingRewardedEvent` wherever required
> Reinstate ParachainStakingRewardedEvent

- db/migrations/1683869421201-Data.js
- schema.graphql
- src/mappings/swaps/index.ts
- src/model/generated/_weight.ts
- src/model/generated/historicalAsset.model.ts
- src/model/generated/historicalPool.model.ts
- src/model/generated/pool.model.ts
- src/server-extension/query.ts
> Finalise migration to base-asset connected fields

- src/mappings/balances/index.ts
- src/mappings/balances/types.ts
- src/processor.ts
- src/types/events.ts
- src/types/support.ts
- src/types/v23.ts
- src/types/v26.ts
- src/types/v29.ts
- src/types/v32.ts
- src/types/v34.ts
- src/types/v35.ts
- src/types/v36.ts
- src/types/v37.ts
- src/types/v38.ts
- src/types/v39.ts
- src/types/v40.ts
- src/types/v41.ts
- src/types/v42.ts
- typegen.json
> Cleanup BalancesEndowedEvent handler code

- .gitignore
- package.json
- scripts/subscribe/db.ts
- scripts/subscribe/proposedMarkets.ts
- yarn.lock
- Replicates storage mechanism from https://github.com/zeitgeistpm/discord-faucet
- Prevents redundant alerts
> Cache market for which proposed alert has been posted

- src/mappings/postHooks/marketResolved.ts
- src/processor.ts
Reconciles token balances for few accounts on bsr. Follows #360.
> Resolve markets via post-hook

- scripts/subscribe/db.ts
- scripts/subscribe/marketStatus.ts
- scripts/subscribe/proposedMarkets.ts
- Locally store marketId with status
- Sync with proposed-market alerts
- Enable logging
> Enable market-status alerts with caching

- src/mappings/postHooks/marketResolved.ts
- src/processor.ts
> Reconcile token balances of resolved markets

- scripts/subscribe/marketStatus.ts
- scripts/subscribe/proposedMarkets.ts
- Validates `AxiosResponse` before updating subscription cache db
- Improves logging
> Handle subscription error on axios webhook request

- src/mappings/predictionMarkets/index.ts
- src/processor.ts
- Drain unresolved tokens from accounts even if pool is absent
- Record transaction history for the account only if there is a change in balance
- Robust modification of balances and assets
> Enhance market-resolved handler

- src/mappings/postHooks/marketResolved.ts
- src/processor.ts
> Reconcile resolution for bsr market 224

- src/mappings/swaps/index.ts
- src/mappings/swaps/types.ts
- src/processor.ts
- src/types/calls.ts
- typegen.json
Closes #388. Checks current pool-share balance before debiting `poolAmount` from it.
> Process & map SwapsPoolExitCall

- src/mappings/balances/index.ts
- src/mappings/currency/index.ts
- src/mappings/parachainStaking/index.ts
- src/mappings/postHooks/marketDestroyed.ts
- src/mappings/postHooks/marketResolved.ts
- src/mappings/predictionMarkets/index.ts
- src/mappings/styx/index.ts
- src/mappings/swaps/index.ts
- src/mappings/system/index.ts
- src/mappings/tokens/index.ts
- src/processor.ts
Reverts zeitgeistpm/zeitgeist-subsquid#399
> Revert "Asynchronously update tokens balances"

- scripts/subscribe/db.ts
- scripts/subscribe/disburseZtg.ts
- scripts/subscribe/marketStatus.ts
- scripts/subscribe/proposedMarkets.ts
- Subscribe to `Deposited` events on account history
- Check if the transaction follows pre-defined rules
- Check if the account is eligible for disbursement
- Sign and send tokens using SDK
- Log and cache results as they happen
> Auto disburse tokens to eligible accounts

- db/migrations/1686976504351-Data.js
- schema.graphql
- src/mappings/swaps/index.ts
- src/model/generated/historicalPool.model.ts
- src/model/generated/market.model.ts
- src/model/generated/pool.model.ts
- src/server-extension/query.ts
- src/server-extension/resolvers/balanceInfo.ts
- src/server-extension/resolvers/index.ts
Closes #401. `assetId` has been by default set to `Ztg` if not available.
> Add resolver to gather balance-history records for an account

- src/mappings/balances/index.ts
- src/mappings/currency/index.ts
- src/mappings/parachainStaking/index.ts
- src/mappings/postHooks/marketDestroyed.ts
- src/mappings/postHooks/marketResolved.ts
- src/mappings/predictionMarkets/index.ts
- src/mappings/styx/index.ts
- src/mappings/swaps/index.ts
- src/mappings/system/index.ts
- src/mappings/tokens/index.ts
- src/processor.ts
Ensure account balances are up-to-date before handling certain events
> Reinstate token balances with asynchronous updation

- db/migrations/1688308084029-Data.js
- schema.graphql
- src/model/generated/account.model.ts
Add `balances` field to `Account` schema
> Collate balances belonging to same account

- db/migrations/1689239378924-Data.js
- schema.graphql
- src/mappings/helper.ts
- src/mappings/predictionMarkets/index.ts
- src/mappings/predictionMarkets/types.ts
- src/mappings/swaps/index.ts
- src/model/generated/_marketEvent.ts
- src/model/generated/historicalMarket.model.ts
- src/processor.ts
- src/types/events.ts
- typegen.json
> Process & map GlobalDisputeStartedEvent

- src/mappings/swaps/index.ts
Extract account address for pool from chain if not found in `SwapsPoolCreateEvent`
> Make rpc call `swaps_getPoolAccountId`

- db/migrations/1689772794114-Data.js
- schema.graphql
- src/mappings/swaps/index.ts
- src/model/generated/historicalSwap.model.ts
Follows https://github.com/zeitgeistpm/ui/pull/1567
> Attach extrinsic info to HistoricalSwap entity

- db/migrations/1689911655024-Data.js
- schema.graphql
- src/mappings/swaps/index.ts
- src/model/generated/historicalPool.model.ts
- src/model/generated/pool.model.ts
- src/processor.ts
- src/server-extension/query.ts
Purges `baseAssetQty` on `Pool` and `HistoricalPool`. Closes #374!
> Handle swaps using baseAsset balance from pool account

- db/migrations/1690384621453-Data.js
- schema.graphql
- src/mappings/postHooks/marketDestroyed.ts
- src/mappings/postHooks/marketResolved.ts
- src/mappings/predictionMarkets/index.ts
- src/mappings/swaps/index.ts
- src/model/generated/historicalMarket.model.ts
- src/server-extension/query.ts
> Join Market with HistoricalMarket schema

- src/mappings/balances/index.ts
- src/mappings/balances/types.ts
- src/processor.ts
- src/types/events.ts
- src/types/v23.ts
- src/types/v34.ts
- typegen.json
> Process & map BalancesReserveRepatriatedEvent

- src/mappings/assetTxPayment/index.ts
- src/mappings/assetTxPayment/types.ts
- src/processor.ts
- src/types/events.ts
- src/types/storage.ts
- src/types/v42.ts
- src/types/v47.ts
- src/types/v48.ts
- typegen.json
> Process & map AssetTxPaymentAssetTxFeePaidEvent

- scripts/validate/balanceHistory.ts
- Refurbishes existing script to accept all types of asset
- Utilises latest `balanceInfo` query resolver
- Reformat and debug overall script
> Validate asset balance history of all squid accounts

- src/mappings/assetTxPayment/index.ts
- src/mappings/assetTxPayment/types.ts
- src/mappings/balances/index.ts
- src/mappings/currency/index.ts
- src/mappings/helper.ts
- src/mappings/parachainStaking/index.ts
- src/mappings/postHooks/balancesUnreserved.ts
- src/mappings/postHooks/marketDestroyed.ts
- src/mappings/postHooks/marketResolved.ts
- src/mappings/predictionMarkets/index.ts
- src/mappings/styx/index.ts
- src/mappings/swaps/index.ts
- src/mappings/system/index.ts
- src/mappings/tokens/index.ts
- src/processor.ts
This has drastically reduced the processing time owing to efficient db calls for `Account`.
> Add balance initialisation to BatchProcessor

- src/mappings/predictionMarkets/index.ts
- src/mappings/predictionMarkets/types.ts
- src/types/events.ts
- src/types/storage.ts
- src/types/v50.ts
Debug storage query made for mapping `outsider` bond on `marketReported` handler.
> Reinit types for MarketCommonsMarketsStorage

- archive/docker-compose.local.yml
- archive/docker-compose.main.yml
- archive/docker-compose.test.yml
Better storage management and data security. Follows https://github.com/zeitgeistpm/zeitgeist-infrastructure/issues/87
> Persist data stored in archive db

- src/mappings/authorized/index.ts
- src/mappings/authorized/types.ts
- src/mappings/helper.ts
- src/processor.ts
- src/types/events.ts
- src/types/v49.ts
- typegen.json
> Process & map AuthorizedAuthorityReportedEvent

- src/mappings/helper.ts
- src/mappings/util.ts
- src/server-extension/resolvers/assetPrice.ts
- src/server-extension/resolvers/index.ts
- src/server-extension/resolvers/marketMetadata.ts
- Fetches price from cache by default (quick retrieval)
- Updates prices on redis if they are older than 10 minutes (cache invalidation)
- Allows user to select supported assets (customisable)
- Displays timestamp to indicate last updated data (clarity)
> Efficiently query prices from Coingecko

- src/mappings/neoSwaps/index.ts
- src/mappings/neoSwaps/types.ts
- src/processor.ts
- src/types/events.ts
- typegen.json
Considers event generated due to addition and removal of liquidity on neo-pools
> Process & map JoinExecutedEvent & ExitExecutedEvent

- db/migrations/1702125775108-Data.js
- db/migrations/1702296178498-Data.js
- schema.graphql
- src/mappings/predictionMarkets/index.ts
- src/model/generated/market.model.ts
Creates new string field `categoryNames` concatenating category names: to make room for filters around it. Closes #471
> Market search based on their category names

- src/mappings/neoSwaps/types.ts
- src/mappings/tokens/index.ts
- src/mappings/tokens/types.ts
- src/processor.ts
- src/types/events.ts
- typegen.json
Closes #474 and Reformats `src/mappings/neoSwaps/types.ts`
> Process & map TokensReservedEvent

- src/processor.ts
> Enhance handling of changes from mappings

- src/consts.ts
- src/server-extension/helper.ts
- src/server-extension/query.ts
- src/server-extension/resolvers/assetPrice.ts
- src/server-extension/resolvers/marketStats.ts
- src/server-extension/resolvers/marketStatsWithOrder.ts
- Compute dollar denominated volume
- Lookup cached prices from Coingecko
> Add volume to market-stats

- db/migrations/1705051650084-Data.js
- db/migrations/1705055422503-Data.js
- schema.graphql
- src/helper.ts
- src/mappings/prediction-markets/decode.ts
- src/mappings/prediction-markets/index.ts
- src/mappings/swaps/index.ts
- src/model/generated/pool.model.ts
- Make `baseAsset` and `totalWeight` on pool schema non-nullable
- Ensure correct mapping of `status` on market schema
> Ensure ArrowSquid compatibility with UI

- src/consts.ts
- src/server-extension/helper.ts
- src/server-extension/query.ts
- src/server-extension/resolvers/assetPrice.ts
- src/server-extension/resolvers/balanceInfo.ts
- src/server-extension/resolvers/index.ts
- src/server-extension/resolvers/issuanceHistory.ts
- src/server-extension/resolvers/marketStatsWithOrder.ts
- src/server-extension/resolvers/priceHistory.ts
Populates asset-issuance vs date. Closes #395
> Resolve asset issuance history

- db/migrations/1706265667468-Data.js
- schema.graphql
- src/helper.ts
- src/main.ts
- src/mappings/prediction-markets/decode.ts
- src/mappings/prediction-markets/helper.ts
- src/mappings/prediction-markets/index.ts
- src/model/generated/_marketEvent.ts
- src/model/generated/market.model.ts
- src/processor.ts
- src/types/prediction-markets/events.ts
- src/types/v51.ts
- typegen.json
Captures early closure of market
> Process & map MarketEarlyCloseScheduledEvent

- src/server-extension/query.ts
- src/server-extension/resolvers/index.ts
- src/server-extension/resolvers/liquidityHistory.ts
Creates a graphql endpoint for fetching liquidity vs time
> Resolve liquidity history

- src/helper.ts
- src/main.ts
- src/post-hooks/index.ts
- src/post-hooks/migrateScoringRule.ts
- src/processor.ts
Follows [changelog](https://github.com/zeitgeistpm/zeitgeist/blob/main/docs/changelog_for_devs.md#v050)
> Migrate CPMM scoring-rule for active markets

- src/helper.ts
- src/main.ts
Supports #445 with additional validation. Fixes #506.
> Check event order while prioritising creator-fees-event over transfer-event 

- src/main.ts
- src/mappings/swaps/index.ts
This should clear zero-balance (stale) assets from accounts. Stats obtained post running balance validation script on testnet shows about 50% reduction of overall assets:
**Before**
```
Total accounts validated: 2363
Total asset balances validated: 13476
```
**After**
```
Total accounts validated: 2048
Total asset balances validated: 7178
```
> Sanitise account-balances

- src/mappings/prediction-markets/decode.ts
- src/mappings/prediction-markets/index.ts
> Encode disputant address with prefix:73

- src/main.ts
- src/mappings/orderbook/decode.ts
- src/mappings/orderbook/index.ts
- src/processor.ts
- src/types/orderbook/events.ts
- typegen.json
Removes order from the history if they have been removed by the maker.
> Process & map OrderbookOrderRemovedEvent

- src/server-extension/query.ts
> Consider zero liquidity on neo-pool while computing market-stats

- db/migrations/1711373978530-Data.js
- schema.graphql
- src/mappings/neo-swaps/index.ts
- src/mappings/prediction-markets/index.ts
- src/mappings/swaps/index.ts
- src/model/generated/asset.model.ts
> Expand asset schema to capture metadata

- scripts/deploy/processor.sh
> Add restart policy to processor container

- src/mappings/prediction-markets/index.ts
> Fix asset-market connection

- scripts/deploy/api.sh
- scripts/deploy/processor.sh
> Setup restart policy around api

- schema.graphql
- src/helper.ts
- src/model/generated/_scoringRule.ts
This should temporarily fix the broken bsr indexer due to recent core release
> Incorporate `AmmCdaHybrid` as scoring-rule

- scripts/validate/balanceHistory.ts
- scripts/validate/balances.ts
Checks assetId on account-balance before querying the respective on-chain pallet
> Utilise new asset classes for balance validation

- src/mappings/asset-tx-payment/decode.ts
- src/mappings/asset-tx-payment/index.ts
Since txn-fees can be paid in assets other than just `ForeignAsset`
> Adapt types decoding for AssetTxFeePaidEvent

- src/main.ts
- src/post-hooks/index.ts
- src/post-hooks/scoringRule.ts
Adapts to latest storage migrations coming from the core
> Migrate from lmsr to ammCdaHybrid

- src/main.ts
- src/mappings/campaign-assets/decode.ts
- src/mappings/campaign-assets/index.ts
- src/processor.ts
- src/types/campaign-assets/events.ts
- typegen.json
Debits burnt amount of `campaign-assets` from the account in question
> Process & map CampaignAssetsBurned

- db/migrations/1716280119351-Data.js
- schema.graphql
- src/main.ts
- src/mappings/court/decode.ts
- src/mappings/court/index.ts
- src/model/generated/_courtEvent.ts
- src/model/generated/historicalCourt.model.ts
- src/processor.ts
- src/types/court/events.ts
- src/types/v49.ts
- src/types/v53.ts
- typegen.json
> Process & map CourtJurorRevealedVoteEvent

- schema.graphql
- src/main.ts
- src/mappings/court/decode.ts
- src/mappings/court/index.ts
- src/model/generated/_courtEvent.ts
- src/processor.ts
- src/types/calls.ts
- src/types/court/calls.ts
- typegen.json
To capture `StakesReassigned` state of the court
> Process & map CourtReassignCourtStakesCall

- src/main.ts
- src/mappings/balances/decode.ts
- src/mappings/court/index.ts
- src/processor.ts
- src/types/balances/events.ts
- typegen.json
Slashes amount arising out of stakes reassignment on court
> Process & map BalancesSlashedEvent

- src/helper.ts
- src/mappings/asset-tx-payment/decode.ts
- src/mappings/asset-tx-payment/index.ts
Consider:
1. USD Coin (Moonbeam Wormhole)
2. USD Coin (Polkadot AssetHub)
> Index V3MultiLocation as asset type
